### PR TITLE
Mavenize.

### PR DESCRIPTION
**Pull request by SimSonic**
Стырил себе для нужд, слегка обновив.
Не вижу ничего страшного, чтобы вернуть с правками :)

### CODE REVIEW

**Comment by SilverCory** [comment]
Why not use Maven or Gradle? O.o

**Comment by Shevchik** [comment]
Maven sucks because it can't work with local only depends normally.

**Comment by SimSonic** [comment]
In fact, can.

[repo local to project's-dir](https://github.com/VoxileRu/VoxileWrapper/tree/master/libs/net/minecraft/launchwrapper/1.11)
[repo url added in pom.xml](https://github.com/VoxileRu/VoxileWrapper/blob/master/pom.xml#L16-L19)
[dependency added in pom.xml](https://github.com/VoxileRu/VoxileWrapper/blob/master/pom.xml#L43-L47)
It is good idea to add local repo url after "official" remote url so building task will fall into local only when remote is unaccessible (if I understand it in right way).

**Comment by Shevchik** [comment]
I mean only local repos. Jenkins just doesn't understand them, at all. Gradle is a lot better, but currently still has poor intergration, maybe it will be better later. So currently only one useful is ant, but for small plugins such as this it is just pointless.

**Comment by SimSonic** [comment]
You can use file:// as repo url and both maven and jenkins eat it.
This is how I compile my projects and publish them in my [maven public repo](https://maven.methuselah.ru/). This is just a folder shared to the web, contents are generated by jenkins.

Don't know about gradle, it is quite hard for me.

Ok, it's your way :) good luck!

**Comment by SilverCory** [comment]
Ant isn't a depend manager, and there's no NMS or OCB in this so you can use Spigot-API or Bukkit-API from the SpigotMC-Hub's nexus...

https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.8.7-R0.1-SNAPSHOT/

**Comment by Shevchik** [comment]
Yea, it isn't, ant is just a tool that allows you to use javac easily. Exactly what i need for a small projects like this.
I'm not gonna write 5 lines for each single dependancy, that's just bullshit.

**Comment by SilverCory** [comment]
Add a build.xml then? xD

**Pull request closed without merging**
